### PR TITLE
Add color to the prompt asking for username

### PR DESCRIPTION
**Pull request by tonyxue**
Entering the username for UID 1000 is where the automated setup process end
normally. Some users may not see the prompt since it mixes with the large amount
of other output. Add a color here just in case they don't notice it.

Patched according to #1664

### CODE REVIEW

**Comment by tonyxue** [comment]
https://github.com/dnschneid/crouton/issues/1770#issuecomment-103969410 proves we really need this one. See the last a few lines of that reply.

And I will wait for #1710 first.

**Comment by firestar115** [comment]
I would like that :smile:

**Comment by DennisLfromGA** [comment]
Me too but it's been awfully quiet on the home front of late, hope everyone and everyting is okay...

**Comment by dnschneid** [comment]
Okay, #1710 is (finally) merged, so you can (finally) update this patch.

**Comment by tonyxue** [comment]
Ok so sorry that it took me half a year to think of I still have this pull request here.:P It has been updated.

**Comment by dnschneid** [comment]
Well, it took me half a year to notice a typo in the commit :)

**Pull request merged**
