### PR TITLE
Add Bionic (Ubuntu 18.04) to release list

### PR DESCRIPTION
**Pull request by icecream95**

### CODE REVIEW

**Comment by icecream95** [comment]
Turns out there are currently hardly any packages so this is probably only suitable for command-line development at the moment - it seems that currently there aren't even any DE's available.

**Comment by EnderNightLord-ChromeBook** [comment]
very true This will take a while

**Comment by icecream95** [comment]
I can't even install the xorg target yet...

**Comment by tsimonq2** [comment]
It's now open for development and daily images have started being produced.

Might be a good thing to have, eventually if it might be used as default. :wink: 

What do you think, @dnschneid?

**Comment by dnschneid** [comment]
Since it's an LTS, bionic is certainly an option for a default in the future.  The migration path for defaults is a little odd, but since we've implemented somewhat reasonable behavior for the precise->xenial default migration, this would probably be straightforward to do as well.

Previously, we skipped trusty and went from precise to xenial due to some of the massive compatibility changes that took place.  Hopefully there's nothing major changing from xenial to bionic that would give us pause?

Anyway, assuming most of the packages are there, we should make the release available to people who like playing with broken things.

**Comment by EnderNightLord-ChromeBook** [comment]
DONE !!!

**Pull request merged**
