### PR TITLE
Create new session, then link user keychain to session keychain

### PR DESCRIPTION
**Pull request by drinkcat**

### CODE REVIEW

**Comment by drinkcat** [comment]
Dear googlebot, @smerrill intent is clear from #3246.

**Comment by dnschneid** [comment]
Googlebot hears ya; googlebot don't care

**Comment by smerrill** [comment]
Confirmed! Thanks for crouton and for pursuing a more complete fix.

**Comment by drinkcat** [comment]
2017-06-16_00-22-19_drinkcat_chroagh_ecryptfs_17 looks ok (17-encryption tests pass)

**Pull request merged**
