### PR TITLE
Change license to 2016

### PR DESCRIPTION
**Pull request by tonyxue**
Just like I did last year. I get uncomfortable with the wrong year :P

And.. OMG it's another year!

### CODE REVIEW

**Comment by tedm** [comment]
lots of pies??

**Comment by tonyxue** [comment]
A big pie, I'd rather say. lol

**Comment by drinkcat** [comment]
LGTM ,-)

**Comment by tedm** [comment]
Well I can add the line for 2016 to the files. But when I go to the files, I can't seem to edit in place. What's the easiest way to access the files?

**Comment by DennisLfromGA** [comment]
@tedm - @tonyxue has *already* submitted the changes in this **PR**, click on the link up top that says:
screenshot 2016-01-23 at 8 29 56 pm

**Comment by tedm** [comment]
Jeez, I did not know this was a race ;)

**Comment by DennisLfromGA** [comment]
It was over before it started, for us... ;)

**Comment by dnschneid** [comment]
Best code review ever

**Pull request merged**
