### PR TITLE
Add new Kali release 'sana'

### PR DESCRIPTION
**Pull request by nromsdahl**
From my testing, it appears adding sana here is all we need to do to add this Kali release.

### CODE REVIEW

**Comment by nromsdahl** [comment]
I just updated this so sana had the 'unsupported release' mark.  Looks like the GUI doesn't have some dependencies, so only cli-extra is working as a target.  I'll look into it more if I have some time.

**Comment by nromsdahl** [comment]
The gui fix was easy... tested with xfce.  Let me know if it needs anything else.

**Comment by drinkcat** [comment]
Not quite sure what is going on, but our autotest failed with sana (similar errors on all platforms):
```
6 [e] Installing sana-amd64 chroot to /usr/local/test-20150812203930 prefix/10-basic.sana.0.0np/chroots/sana
6 [e] Downloading latest debootstrap...
8 [e] 2015-08-12 21:15:32 URL:http://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [62068] -> "-" [1]
8 [e] Patching debootstrap...
8 [e] Downloading bootstrap files...
8 [e] W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
8 [e] I: Retrieving Release 
9 [e] I: Retrieving Packages 
15 [e] I: Validating Packages 
18 [e] I: Resolving dependencies of required packages...
23 [e] I: Resolving dependencies of base packages...
27 [e] I: Found additional required dependencies: acl adduser dmsetup insserv libaudit-common libaudit1 libbz2-1.0 libcap2 libcap2-bin libcryptsetup4 libdb5.3 libdebconfclient0 libdevmapper1.02.1 libgcrypt20 libgpg-error0 libkmod2 libncursesw5 libprocps3 libsemanage-common libsemanage1 libslang2 libsystemd0 libudev1 libustr-1.0-1 procps systemd systemd-sysv udev 
27 [e] I: Found additional base dependencies: libdns-export100 libestr0 libffi6 libgmp10 libgnutls-deb0-28 libgnutls-openssl27 libhogweed2 libicu52 libidn11 libirs-export91 libisc-export95 libisccfg-export90 libjson-c2 liblogging-stdlog0 liblognorm1 libmnl0 libnetfilter-acct1 libnettle4 libnfnetlink0 libp11-kit0 libpsl0 libtasn1-6 
27 [e] I: Checking component main on http://http.kali.org...
....
36 [e] I: Retrieving base-files 1:2.0~rc1+1
37 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
37 [e] I: Retrieving base-files 1:2.0~rc1+1
38 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
38 [e] I: Retrieving base-files 1:2.0~rc1+1
40 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
40 [e] I: Retrieving base-files 1:2.0~rc1+1
41 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
41 [e] I: Retrieving base-files 1:2.0~rc1+1
42 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
42 [e] I: Retrieving base-files 1:2.0~rc1+1
43 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
43 [e] I: Retrieving base-files 1:2.0~rc1+1
45 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
45 [e] I: Retrieving base-files 1:2.0~rc1+1
46 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
46 [e] I: Retrieving base-files 1:2.0~rc1+1
47 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
47 [e] I: Retrieving base-files 1:2.0~rc1+1
48 [e] W: Retrying failed download of http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb
48 [e] W: http://http.kali.org/pool/main/b/base-files/base-files_2.0~rc1+1_amd64.deb was corrupt
48 [e] W: Couldn't download package base-files (ver 1:2.0~rc1+1 arch amd64)
...
221 [e] E: Couldn't download packages: base-files
```

Will queue a second run just to make sure it's not a flake.

**Comment by nromsdahl** [comment]
I just cloned, compiled and tested it again, and I am not seeing that issue.  Let me know how the second run goes:

chronos@localhost ~/Downloads $ sudo sh -e crouton -r sana -t xfce -n sana1
Installing sana-amd64 chroot to /usr/local/chroots/sana1
Downloading latest debootstrap...
2015-08-22 08:17:11 URL:http://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [62068] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving Release 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: acl adduser dmsetup insserv libaudit1 libaudit-common libbz2-1.0 libcap2 libcap2-bin libcryptsetup4 libdb5.3 libdebconfclient0 libdevmapper1.02.1 libgcrypt20 libgpg-error0 libkmod2 libncursesw5 libprocps3 libsemanage1 libsemanage-common libslang2 libsystemd0 libudev1 libustr-1.0-1 procps systemd systemd-sysv udev 
I: Found additional base dependencies: libdns-export100 libestr0 libffi6 libgmp10 libgnutls-deb0-28 libgnutls-openssl27 libhogweed2 libicu52 libidn11 libirs-export91 libisccfg-export90 libisc-export95 libjson-c2 liblogging-stdlog0 liblognorm1 libmnl0 libnetfilter-acct1 libnettle4 libnfnetlink0 libp11-kit0 libpsl0 libtasn1-6 
I: Checking component main on http://http.kali.org...
I: Retrieving acl 2.2.52-2
I: Validating acl 2.2.52-2
I: Retrieving adduser 3.113+nmu3
I: Validating adduser 3.113+nmu3
I: Retrieving apt 1.0.9.10+kali1~r2u1
I: Validating apt 1.0.9.10+kali1~r2u1
I: Retrieving apt-utils 1.0.9.10+kali1~r2u1
I: Validating apt-utils 1.0.9.10+kali1~r2u1
I: Retrieving aptitude-common 0.6.11-1
I: Validating aptitude-common 0.6.11-1
I: Retrieving base-files 1:2.0
I: Validating base-files 1:2.0
I: Retrieving base-passwd 3.5.37
I: Validating base-passwd 3.5.37
I: Retrieving bash 4.3-11+b1
I: Validating bash 4.3-11+b1
I: Retrieving bsdmainutils 9.0.6
I: Validating bsdmainutils 9.0.6
I: Retrieving bsdutils 1:2.25.2-6
I: Validating bsdutils 1:2.25.2-6
I: Retrieving coreutils 8.23-4
I: Validating coreutils 8.23-4
I: Retrieving cpio 2.11+dfsg-4.1
I: Validating cpio 2.11+dfsg-4.1
I: Retrieving cron 3.0pl1-127
I: Validating cron 3.0pl1-127
I: Retrieving dash 0.5.7-4+b1
I: Validating dash 0.5.7-4+b1
I: Retrieving debconf 1.5.56
I: Validating debconf 1.5.56
I: Retrieving debconf-i18n 1.5.56
I: Validating debconf-i18n 1.5.56
I: Retrieving debian-archive-keyring 2014.3
I: Validating debian-archive-keyring 2014.3
I: Retrieving debianutils 4.4+b1
I: Validating debianutils 4.4+b1
I: Retrieving diffutils 1:3.3-1+b1
I: Validating diffutils 1:3.3-1+b1
I: Retrieving dmidecode 2.12-3
I: Validating dmidecode 2.12-3
I: Retrieving dmsetup 2:1.02.90-2.2
I: Validating dmsetup 2:1.02.90-2.2
I: Retrieving dpkg 1.17.25
I: Validating dpkg 1.17.25
I: Retrieving e2fslibs 1.42.12-1.1
I: Validating e2fslibs 1.42.12-1.1
I: Retrieving e2fsprogs 1.42.12-1.1
I: Validating e2fsprogs 1.42.12-1.1
I: Retrieving findutils 4.4.2-9+b1
I: Validating findutils 4.4.2-9+b1
I: Retrieving gcc-4.8-base 4.8.4-1
I: Validating gcc-4.8-base 4.8.4-1
I: Retrieving gcc-4.9-base 4.9.2-10
I: Validating gcc-4.9-base 4.9.2-10
I: Retrieving gnupg 1.4.18-7
I: Validating gnupg 1.4.18-7
I: Retrieving gpgv 1.4.18-7
I: Validating gpgv 1.4.18-7
I: Retrieving grep 2.20-4.1
I: Validating grep 2.20-4.1
I: Retrieving groff-base 1.22.2-8
I: Validating groff-base 1.22.2-8
I: Retrieving gzip 1.6-4
I: Validating gzip 1.6-4
I: Retrieving hostname 3.15
I: Validating hostname 3.15
I: Retrieving ifupdown 0.7.53.1
I: Validating ifupdown 0.7.53.1
I: Retrieving init 1.22
I: Validating init 1.22
I: Retrieving init-system-helpers 1.22
I: Validating init-system-helpers 1.22
I: Retrieving initscripts 2.88dsf-59kali1
I: Validating initscripts 2.88dsf-59kali1
I: Retrieving insserv 1.14.0-5
I: Validating insserv 1.14.0-5
I: Retrieving iproute2 3.16.0-2
I: Validating iproute2 3.16.0-2
I: Retrieving iptables 1.4.21-2+b1
I: Validating iptables 1.4.21-2+b1
I: Retrieving iputils-ping 3:20121221-5+b2
I: Validating iputils-ping 3:20121221-5+b2
I: Retrieving isc-dhcp-client 4.3.1-6
I: Validating isc-dhcp-client 4.3.1-6
I: Retrieving isc-dhcp-common 4.3.1-6
I: Validating isc-dhcp-common 4.3.1-6
I: Retrieving kali-archive-keyring 2015.2
I: Validating kali-archive-keyring 2015.2
I: Retrieving kmod 18-3
I: Validating kmod 18-3
I: Retrieving less 458-3
I: Validating less 458-3
I: Retrieving libacl1 2.2.52-2
I: Validating libacl1 2.2.52-2
I: Retrieving libapt-inst1.5 1.0.9.10+kali1~r2u1
I: Validating libapt-inst1.5 1.0.9.10+kali1~r2u1
I: Retrieving libapt-pkg4.12 1.0.9.10+kali1~r2u1
I: Validating libapt-pkg4.12 1.0.9.10+kali1~r2u1
I: Retrieving libattr1 1:2.4.47-2
I: Validating libattr1 1:2.4.47-2
I: Retrieving libaudit-common 1:2.4-1
I: Validating libaudit-common 1:2.4-1
I: Retrieving libaudit1 1:2.4-1+b1
I: Validating libaudit1 1:2.4-1+b1
I: Retrieving libblkid1 2.25.2-6
I: Validating libblkid1 2.25.2-6
I: Retrieving libboost-iostreams1.55.0 1.55.0+dfsg-3
I: Validating libboost-iostreams1.55.0 1.55.0+dfsg-3
I: Retrieving libbz2-1.0 1.0.6-7+b3
I: Validating libbz2-1.0 1.0.6-7+b3

**Comment by drinkcat** [comment]
Second try passed, so probably a transient network error.

**Comment by dnschneid** [comment]
I merged the earlier commit but kept it as unsupported for now.  We need to test all the targets explicitly to make sure they all work (separate PR if there are fixes)

**Pull request closed without merging**
