### PR TITLE
Add dialout group to sync, for use with programming microcontrollers

### PR DESCRIPTION
**Pull request by WRansohoff**
This lets the crouton environment work with IDEs like Arduino, NodeMCU, etc. I've only tested on an Asus C100 Flip (ARM.)

### CODE REVIEW

**Comment by dnschneid** [comment]
Are tape and tty also needed?  Or just dialout?

**Comment by WRansohoff** [comment]
They were already in the file; I just moved them down a line to keep the line length about the same.

**Comment by dnschneid** [comment]
haha I can't read

Yes, this looks good.  @smibarber can you think of any downsides here?

**Comment by smibarber** [comment]
Nope, seems fine to me.

**Pull request merged**
