### PR TITLE
EOL precise

### PR DESCRIPTION
**Pull request by dnschneid**
Marks precise as EOL'd!

precise!

### CODE REVIEW

**Comment by DennisLfromGA** [comment]
Great timing 😜
image

**Comment by drinkcat** [comment]
LGTM, actually ,-)

**Comment by dnschneid** [comment]
I'm actually concerned there's no properly documented migration path from precise, though.  Especially since it looks like upgrading doesn't work; there needs to be documentation somewhere obvious so we don't get (quite as large) a torrent of bug reports.

**Comment by dnschneid** [comment]
Any thoughts towards migration?  @DennisLfromGA did you ever figure out a decent upgrade path?

**Comment by dnschneid** [comment]
OK at this point we should probably just merge this.

**Comment by DennisLfromGA** [comment]
Sorry, I couldn't find a decent upgrade path, I tried and failed.
Going to almost any release from precise was problematic for me.

**Pull request merged**
