### PR TITLE
update 	xf86-video-dummy-0.4.0.tar.gz , wrapper release and version in target xiwi -maintenance-

### PR DESCRIPTION
**Pull request by TomTravis**
patching fails
Patching Xorg dummy driver (xrandr 1.2 support)...
patching file src/dummy_driver.c
Hunk #1 succeeded at 31 with fuzz 2 (offset -3 lines).
Hunk #2 succeeded at 439 (offset 262 lines).
Hunk #3 succeeded at 656 (offset 265 lines).
Hunk #4 succeeded at 722 (offset 266 lines).
Hunk #5 succeeded at 751 (offset 266 lines).
Hunk #6 succeeded at 891 (offset 267 lines).
Hunk #7 succeeded at 977 (offset 313 lines).
Hunk #8 FAILED at 690.
1 out of 8 hunks FAILED -- saving rejects to file src/dummy_driver.c.rej
Failed to complete chroot setup.

xf86-video-dummy-0.4.0.tar.gz | 2022-04-05 17:16 | 371K |  
-- | -- | -- | --

[xf86-video-dummy-0.4.0.tar.gz](https://xorg.freedesktop.org/releases/individual/driver/xf86-video-dummy-0.4.0.tar.gz)	2022-04-05 17:16	371K

### CODE REVIEW

**Comment by TomTravis** [comment]
patch need work  for new 2022 driver

**Comment by TomTravis** [comment]
https://xorg.freedesktop.org/releases/individual/driver/
many new drivers

**Comment by dnschneid** [comment]
Whoa!  First release from xf86-video-dummy in 4 years!  [Diff here](https://gitlab.freedesktop.org/xorg/driver/xf86-video-dummy/-/compare/4a6df6b4eecae769771eba0136bf8271d01258fb...68e02860d9ee6d65733457e689d180653fc9829f?from_project_id=602).

The only change of any substance is [their own implementation of randr](https://gitlab.freedesktop.org/xorg/driver/xf86-video-dummy/-/commit/327a25c4c3ab0b79a1103794449a1f7ccd6faff3) which is probably why that last hunk is failing, and the rest of the patches are probably now irrelevant. @drinkcat not sure why you never upstreamed your patches ( :P ) but can you do a sanity check to make sure we could get rid of all of [the baggage](https://github.com/dnschneid/crouton/blob/master/targets/xiwi#L73) the xiwi target is carrying?

As a bonus, looks like we could also skip installing `x11proto-xf86dga-dev`.

@TomTravis while bumping the xf86-video-dummy revision would be nice for minimizing the amount of custom patching that crouton has to do, I don't see this as actually improving compatibility with anything you're working on.  Regardless, if you'd like to contribute the version bump, please clean up your branch to limit it only to the changes surrounding dummy.  I think the needed changes are to (1) bump the url (as you've done), (2) remove the entire patch blob, and (3) get rid of x11proto-xf86dga-dev from the install.  Not sure if anything else is needed.

**Comment by TomTravis** [comment]
yes i will help bullseye and sid also Kali may install diff Debootstrap

Kali patches the kernel with KMS this take like 10min 
it does not use the dummy best i call tell

**Comment by TomTravis** [comment]
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: No GPUs detected via PCI (t=1.86803) |[1][GFX1-]: glxtest: process failed (received signal 11) (t=1.86915) [GFX1-]: glxtest: process failed (received signal 11)

**Comment by TomTravis** [comment]
new proposed changes for wrapper and release and version
not need for forked repos the over writes local edits

**Comment by TomTravis** [comment]
https://github.com/dnschneid/crouton/pull/3500

**Comment by TomTravis** [comment]
hello 
I have update my local repo and will be updating my git repo
the dev env for crouton is such the make clean and make all give errors
I was able to update files after crouton.build is made
the make has compile errors and the install process show the same errors 
Screenshot 2022-11-15 12 05 35 PM
Screenshot_2022-11-15_12-08-56
the chroot works just fine

my dev env is back

**Comment by TomTravis** [comment]
ok this is a bit to busy i will close and submit again
via new release

**Pull request closed without merging**
