### PR TITLE
vivid added below utopic

### PR DESCRIPTION
**Pull request by tedm**
vivid*|test

### CODE REVIEW

**Comment by smibarber** [comment]
Looks good to me, but will wait for @dnschneid to take a gander.

**Comment by tedm** [comment]
@smibarber OK, thanks. Browsing the open issues lists for more `pie` items.

**Comment by dnschneid** [comment]
Thanks!

**Comment by dnschneid** [comment]
@tedm: do you want your full name in CONTRIBUTORS, or just "tedm"?

**Comment by tedm** [comment]
@dnschneid full name is fine. Thanks.

**Pull request merged**
