### PR TITLE
ubuntu (22.04 LTS) Jammy Jellyfish? crouton -r target

### PR DESCRIPTION
**Pull request by TomTravis**
add -r target ubuntu (22.04 LTS) Jammy Jellyfish?  Crouton shell and the install script

### CODE REVIEW

**Review by TomTravis — COMMENTED** [review]
please my NAME to this list

**Comment by DennisLfromGA** [comment]
@TomTravis,

Was the intention of this pull request to add 'jammy' to the [Ubuntu releases](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/releases)?

If so, it appears you have included files modified from 27 other commits but didn't add 'jammy'. 🤔

Just curious about these changes.

There is another PR listed below that only adds 'jammy', check it out if you like:   
- #4727

*Hope this helps,*
-**DennisLfromGA**

**Comment by TomTravis** [comment]
you are welcome to adjust the pull request, I just did what i thought was needed 

Im not fully aware on how the compile crouton and/or get the installer correct for JAMMY
The other pull request was review it was after mine was submitted, 

The update for Firefox on buster ARM64 Appears to be stable no reset after and apt upgrade

**Comment by TomTravis** [comment]
[gutsy.txt](https://github.com/dnschneid/crouton/files/8648719/gutsy.txt)

was update to add jammy it had warning from the crouton script however it did start the install and a debootstrap error

sudo croutonj -r list
/usr/local/bin/croutonj: 99: .: /tmp/croutonj.MXr/installer/main.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/usr/local/bin/croutonj: 113: .: /tmp/croutonj.MXr/installer/functions: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy! jessie! stretch! buster
    bullseye bookworm sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
    disco! eoan! focal* groovy! hirsute! impish*** jammy**
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.

### sudo croutonj -r jammy -t core
/usr/local/bin/croutonj: 99: .: /tmp/croutonj.S2V/installer/main.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/usr/local/bin/croutonj: 113: .: /tmp/croutonj.S2V/installer/functions: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/usr/local/bin/croutonj: 290: .: /tmp/croutonj.S2V/installer/ubuntu/defaults: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/usr/local/bin/croutonj: 319: .: /tmp/croutonj.S2V/targets/core: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/usr/local/bin/croutonj: 8: .: /tmp/croutonj.S2V/targets/common: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/bin/sh: 0: /tmp/croutonj.S2V/host-bin/mount-chroot: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/tmp/croutonj.S2V/host-bin/mount-chroot: 34: .: /tmp/croutonj.S2V/host-bin/../installer/functions: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
Installing jammy-amd64 chroot to /usr/local/chroots/jammy
/usr/local/bin/croutonj: 634: .: /tmp/croutonj.S2V/installer/ubuntu/bootstrap: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease
I: Retrieving Packages
^CE: Interrupt caught ... exiting


I: Extracting base-files...
E: Extracting .//var/cache/apt/archives/base-files_12ubuntu4_amd64.deb requires the zstdcat command, which is not available
debootstrap error log:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58236  100 58236    0     0  71807      0 --:--:-- --:--:-- --:--:-- 75337

**Comment by TomTravis** [comment]
jammy was added to the release file
[releases.txt](https://github.com/dnschneid/crouton/files/8648750/releases.txt)

**Comment by TomTravis** [comment]
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1823593.html

**Comment by TomTravis** [comment]
http://ports.ubuntu.com/ubuntu-ports/dists/
 jammy is there

zstdcat command, fix and it should install

**Comment by TomTravis** [comment]
the install errors are gone the core installed the xorg mouse-v files could not be found when x11,audio,xfce was chroot -u
the crouton file sudo mount -o remount,exec,suid,dev,symfollow /media/removable/sd200 is installed on sd200
it run without errors after remount
chronos@localhost / $ sudo mount -o remount,exec,suid,dev,symfollow /media/removable/sd200/
chronos@localhost / $ sudo mount -o remount,exec,suid,dev,symfollow /tmp 
 Unable to locate package xserver-xorg-input-vmmouse x11 error

jammy)coco@localhost:~$ df
Filesystem                                             1K-blocks     Used        Available Use% Mounted on
/dev/mmcblk0p1                                          51446208 15528292         33274872  32% /
shmfs                                                    1989620    65120          1924500   4% /dev/shm
tmpfs                                                    1989620    10920          1978700   1% /tmp
tmpfs                                                     397924        8           397916   1% /run
tmpfs                                                       5120        0             5120   0% /run/lock
tmpfs                                                    1989620      664          1988956   1% /var/host/dbus
/dev/mapper/encstateful    

(jammy)coco@localhost:~$ uname -a
Linux localhost 5.10.101-14962-gede4ccb2bf53 #1 SMP PREEMPT Wed Apr 13 19:47:19 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
(jammy)coco@localhost:~$

**Comment by TomTravis** [comment]
gusty script was updated for  jammy  Install 
release file added jammy
ln-s to gusty was cp and renamed from xenial  to jammy in scripts
make crouton arm64 machine
X11 errors now

**Comment by TomTravis** [comment]
xiwi work on jammy with mate audio is good
Screenshot at 2022-05-09 02-29-00

**Pull request closed without merging**
