### PR TITLE
Temporarily mitigate #3352 by ignoring the error

### PR DESCRIPTION
**Pull request by eyqs**
This commit can be reverted later after edid_utils.c has been updated.

### CODE REVIEW

**Comment by eyqs** [comment]
I signed it!

**Comment by dnschneid** [comment]
Thanks!  Running tests...

**Comment by eyqs** [comment]
@dnschneid How are the tests?

**Comment by dnschneid** [comment]
Test infra was down...looks good now.  Thanks for the workaround!

**Pull request merged**
