### PR TITLE
Updated README with download instruction from shell

### PR DESCRIPTION
**Pull request by idvoretskyi**
Sometimes it's easier to install crouton directly from the command line. These instructions will allow you to do that easier.

### CODE REVIEW

**Comment by DennisLfromGA** [comment]
@idvoretskyi,

I *definitely* think it's best to download 'crouton', either by clicking the link or manually via wget, etc., in the _**~/Downloads**_ folder and then launching it using: `sudo sh ~/Downloads/crouton ...`

For one, it's just simpler and doesn't add unnecessary steps. 
And two, the `dev_install` command is *dangerous* since it will wipe out anything under `/usr/local/`, which will remove the `chroots` and `bin` folders if they are present. 

However, that's just my opinion.

*Hope this helps,*
-**DennisL**

**Comment by dnschneid** [comment]
Yeah, I don't think this really adds anything to the README, and poking at dev_install is indeed dangerous.

**Comment by idvoretskyi** [comment]
@DennisLfromGA @dnschneid well, I would suggest having the "CLI-friendly" way to download Crouton in README. Anyway, I can adopt it and skip the "dev_install" section.

**Comment by dnschneid** [comment]
Thanks, but it's not really clear to me why you'd need a CLI-friendly way to download crouton in the README, since you basically have to be in a web browser in order to read it.  Wouldn't it be more work to copy-paste whatever commands are there?

Seems like something you could put in the wiki, but not that useful in the README.

**Pull request closed without merging**
