### PR TITLE
Bind mount /var/run/chrome

### PR DESCRIPTION
**Pull request by dreveman**

### CODE REVIEW

**Comment by dnschneid** [comment]
Will this interfere at all with Chrome running inside the chroot?

**Comment by dreveman** [comment]
A chromeos build of chrome inside the chroot would interfere with this if XDG_RUNTIME_DIR is set to /var/run/chrome. That's to be expected though. XDG_RUNTIME_DIR is not set by default in the chroot. It can be set to /var/run/chrome if clients should be using the host instance of chrome as wayland server or it can be set to something else if that's no desirable. This change doesn't force any specific behavior. It just makes it possible to set it in a way that allows the host instance to used as display server for wayland clients.

**Comment by dnschneid** [comment]
Oh, of course, duh :)
Thanks!

**Comment by dnschneid** [comment]
Now we just need an equivalent to the [old host-x11 script](https://github.com/dnschneid/crouton/blob/58b76a38ce4125373da8dc4023a9ab9570269482/chroot-bin/host-x11)...

**Comment by DennisLfromGA** [comment]
Yup, so I can again [abuse the `host-x11` script](https://github.com/dnschneid/crouton/issues/1567#issuecomment-88235073 ) or it's equivalent with 'screencast'. ;-)

**Pull request merged**
