### PR TITLE
add jammy jellyfish, maybe

### PR DESCRIPTION
**Pull request by USMP-lancer**
im not too familiar with these but this should add the thing(based on the release commits you made)

### CODE REVIEW

**Comment by TomTravis** [comment]
Screenshot at 2022-05-09 02-29-00

**Comment by dnschneid** [comment]
That *could* be all that's required, or there might be other things preventing Jammy from installing.  Have you tested it?

**Comment by luisodls** [comment]
I tried running:
`sudo crouton -r Jammy -t xfce`

with crouton downloaded from:
[](https://goo.gl/fd3zc)

and it tells me:
```
Downloading latest crouton installer...
############################################################################################################################### 100.0%
Jammy does not belong to any supported distribution.
```

Did I miss something? Wrong branch?

**Comment by DennisLfromGA** [comment]
@luisodls,

Linux is *very* case sensitive, so try your command with a lowercase 'j' in  'jammy', see below:

Screenshot 2022-05-24 1 49 31 PM

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@luisodls,

Note that this pull request has not been merged yet so it will not be in the current version of crouton, you will have to use [the OPs branch](https://github.com/USMP-lancer/crouton/tree/patch-1) to try it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TomTravis** [comment]
yes you have some update in the link script and keycode
my fork works crouton does not work to the best to the best of knowledge
here my fork update
https://drive.google.com/file/d/1_rfoNvtl8CaT8lDeB33dGj1K901Cc7dc/view?usp=sharing

**Pull request closed without merging**
