### PR TITLE
i do the commits today and push

### PR DESCRIPTION
**Pull request by TomTravis**
This the update mate desktop targets with Jammy and xiwi runs super nice, some of the targets need to be updated

the crouton image is on a google drive
https://drive.google.com/file/d/1_rfoNvtl8CaT8lDeB33dGj1K901Cc7dc/view?usp=sharing Crouton_jammy

I did -r jammy -t mate, audio, xiwi,touch
 x11 xiwi starts up just fine

I have not found a web broswer yet

this is one a arm64 lenovo with crostini enabled

My older lenovo amd64 will not install jammy  stop after stage 1 extractor fails debootstrap fails Im sure this can be address i have zstd 
Screenshot at 2022-05-11 13-57-52
installed 

have fun

### CODE REVIEW

**Comment by TomTravis** [comment]
when i run local make some times if wipe the changes i have to fix this on git i now have one branch

**Comment by TomTravis** [comment]
Screenshot at 2022-05-11 18-23-20

**Comment by dnschneid** [comment]
Sorry, but this is not mergeable.  Please organize your changes into minimally-sized pull requests; as it is here you are adding or modifying 417 files, most of which seem to be build files and changes unrelated to getting jammy to work.

**Comment by narloid** [comment]
hi

**Pull request closed without merging**
