### PR TITLE
Added "Arc" target + Changed how Alsaconf deals with "non-existing" directories.

### PR DESCRIPTION
**Pull request by Hacksawfred3232**
- Added new target "arc" + Modified enter-chroot and post-common to integrate this new target.
This target enables support for accessing the virtual sdcard used by the App Run-time for Chrome.
By default, most of the files that the files apps interacts with is stored in here.

- Changed how alsaconf deals with "non-existing" directories
Due to a bug that i can not determine the origin of, ALSA may drop the 10-cras.conf file into /tmp as a incorrectly triggered fail-safe.
A through analysis shows the following:
  - The directories are present, but the installer logic fails to detect it on the first run of that chroot's setup process.
  - Additionally, while /etc/alsa/conf.d is always first to be checked, the actual format is that all conf files are symlinked to their respective counterparts
   in /usr/share/alsa/alsa.conf.d

I have made the following change in accordance:
  - I have changed the default action for no directories found. Instead of changing the alsaconf var to /tmp, the directories are forcefully made and the default
   structure is installed. However, if the checks pass (Most likely due to the chroot being updated, which means the directories already exist), then the config
   file is written to the existing directory.

Additional post-commit notes:
Does anyone know why the installer is bugging out around the alsaconf bit? As I referenced in my commit, I could not determine what was causing the problem of the installer not detecting the ALSA configuration directory. Maybe someone with more knowledge of bash might know, cause I don't.

### CODE REVIEW

**Comment by DennisLfromGA** [comment]
I would suggest submitting the arc target and alsaconf fix as separate pull requests, I think they'd have a better chance of getting merged that way.

**Comment by Hacksawfred3232** [comment]
Concerning that i have no real idea on how to do that, i will pass. Unless you know how to split commits into two different pull requests?

**Comment by Hacksawfred3232** [comment]
@DennisLFromGA I guess dnschnied is currently tied up with other things? If so, I can make a release branch on my end for my personal use for now while you guys sort things out.

**Comment by DennisLfromGA** [comment]
@Hacksawfred3232,

Yeah, that might be best in the interim at least.
I'm just a contributor, not a real crouton dev so can't help much here, sorry.

-**DennisLfromGA**

**Comment by Hacksawfred3232** [comment]
Late response (Been busy with exams), but i have gone ahead and updated my version of the releases branch. I guess nothing else can be done for now, as dnschnied seems to be busy with other projects.

**Pull request closed without merging**
