### PR TITLE
Avoid disabling SELinux for rest of system

### PR DESCRIPTION
**Pull request by dreveman**
Bind mount the directory read-only in the chroot.

### CODE REVIEW

**Comment by DennisLfromGA** [comment]
`enter-chroot` is now working again for me and without having to unmount selinix.

Note: I do not yet have Android apps on my Dell CB13 so I cannot attest to it working with Google Play - yet.

**Comment by dnschneid** [comment]
Would this be preferred over #2735?

**Comment by greymouser** [comment]
@dnschneid From some simple manual tests, this fix also seems to work. I think this fix is to be preferred over my suggested changes in #2735 -- it's less changes overall. We should definitely get one of these out ASAP. :-)

@dreveman You may want to also change the comment above the conditional you modified to the title of this issue ("Avoid disabling SELinux for rest of system"), instead of what it is now.

**Comment by dnschneid** [comment]
Sounds like this is the way to go then.  Thanks all for testing!

**Comment by rickyz** [comment]
Mounting selinuxfs read only in the chroot causes issues with certain distros, see https://github.com/dnschneid/crouton/issues/2655. The correct solution is in fact to unmount selinuxfs inside the chroot, as done in https://github.com/dnschneid/crouton/pull/2735.

**Comment by ohan2** [comment]
I'm terribly sorry for making this entirely unrelated inquiry, but I've done some research and asked the question elsewhere and I've yet to find a conclusive answer. So I figured that someone here at least would have the relevant expertise to finally address this concern of mine.

Has there been and could there be a firmware-level malware/rootkit on a Chromebook which would survive power-washing and compromise the system even while running stock? 

I know very little about how the firmware operates, but this page (https://www.chromium.org/chromium-os/chromiumos-design-docs/verified-boot) explicitly states that the Chromebook's verified boot solution relies on the assumption that the firmware hasn't been tampered with, and there have been reports of UEFI rootkits on PCs, so something of a similar nature isn't out of the question for Chromebooks. My Chromebook is my primary computer device, and due to this and that I've become pretty wary over the years.

Sorry...

**Comment by divx118** [comment]
@ohan2 AFAIK there has never been any firmware-level malware/rootkit on a chromebook. However this is not a 100% insurance that there never will be. There will always security holes to be fixed on a system. Also if you have put your chromebook in developer mode to also use crouton, This is a good read https://github.com/dnschneid/crouton/wiki/Security
That said I feel pretty safe in using my chromebook in developer mode and never had any security issues.
IMO chromebooks are very safe to use.
I think you never find any conclusive answer, because there isn't one. There is on every system always a opportunity of braking through the security. How hard it will be, depends also on how much time/resources people want to spend breaking through the security and if they have physical access  or not.

**Comment by ohan2** [comment]
@divx118 Thanks for the answer. That's a big relief since I bought my Chromebook second-handedly, and I conduct all of my personal and financial matters through it.

**Comment by dnschneid** [comment]
For the ultimate paranoid: you can guarantee that your Chromebook is only running Google-supplied code if you:

1. Never disassemble your system (nor let anybody else disassemble your system), ensuring the write protect screw stays in place
2. Shut down the system and then hit Power+Refresh to restart the chain of trust after using crouton
3. At each "scary boot screen", hit TAB to confirm that verified boot is enabled
4. Do your banking/whatever prior to entering a chroot

Of course, this assumes someone hasn't managed to steal the Google signing keys, which would be a Bad Thing for everyone.  It also assumes someone hasn't tampered with the Chromebook at the factory, installing their own keys and managing a shadow update server that re-signs all the official updates unchanged until that one day when they decide they want to steal @ohan2's checking account.

**Comment by ohan2** [comment]
@dnschneid I'm not too worried about that myself, since I'm only concerned is about the hypothetical small-time identity thieves or hackers, since I wasn't sure if some hacked firmware for Chromebooks had been released into the wild.

But if someone actually manages to steal the signing keys... yeah, I'll be reassessing my relationship with Google.

**Pull request merged**
