### PR TITLE
Added startxiwi references

### PR DESCRIPTION
**Pull request by DennisLfromGA**
Added startxiwi to HOSTBIN and tweaked TIPS to add the same.

### CODE REVIEW

**Comment by dnschneid** [comment]
This really should be in the other PR.

**Comment by DennisLfromGA** [comment]
okay, sorry...

**Comment by DennisLfromGA** [comment]
Sorry again but I can't figure out how to add it to PR https://github.com/dnschneid/crouton/pull/1596

**Comment by dnschneid** [comment]
If you're using the github interface, you'll need to create a PR on your own side to merge patch-2 into patch-1.  If you're doing it from the command line, you can do `git checkout patch-1; git merge patch-2`

**Pull request closed without merging**
