### PR TITLE
Acer Chromebook 14 (edgar) specific touchpad settings.

### PR DESCRIPTION
**Pull request by Happy-Ferret**
The following PR should fix the touchpad problems mentioned in issue #2657.

I've chosen to implement a custom path as I felt setting `FingerLow` and `FingerHigh` alone didn't offer a sufficient enough usability improvement.

### CODE REVIEW

**Comment by dnschneid** [comment]
Wow, did you customize each one of those values?

**Comment by Happy-Ferret** [comment]
I manually tested every one of them.
Why? Is that a problem?

**Comment by drinkcat** [comment]
The question is, does it work reliably with just `FingerLow=5 FingerHigh=10`? Are all the other settings really necessary?

**Comment by DennisLfromGA** [comment]
I was wondering if those settings (`FingerLow=5 FingerHigh=10`) could also be applied to some other models too, like I mentioned in this comment - https://github.com/dnschneid/crouton/issues/214#issuecomment-232519598

Some have already been applied but these may need the settings too -
- chell (HP Chromebook 13)
- terra (ASUS Chromebook C202SA)
- reks (Lenovo N22 Chromebook)

**Pull request closed without merging**
