### PR TITLE
Kali Sana tested

### PR DESCRIPTION
**Pull request by Alfriadox**
Kali Sana works well with xfce4 and xiwi. 

Removing from unsupported

### CODE REVIEW

**Comment by Alfriadox** [comment]
is this similar to #2016

**Comment by dnschneid** [comment]
Thanks, but testing needs to be done across all targets and multiple architectures.  Once the autotest infrastructure is back up, I'll do a full test run and merge if things look good.  In the meantime, please sign the CLA.

**Comment by Alfriadox** [comment]
Signed the CLA. Check. (Am I an official contributor now?...)

**Comment by dnschneid** [comment]
(I guess so!)  Thanks!

**Pull request merged**
