### PR TITLE
Kali-current is now sana

### PR DESCRIPTION
**Pull request by tonyxue**
Thus we only need sana now.

See https://github.com/dnschneid/crouton/issues/1868#issuecomment-152956650

### CODE REVIEW

**Comment by dnschneid** [comment]
This is a bit sticky, as there's no upgrade path.  Maybe just mark it as unsupported so that users get the appropriate "might be EOL" message?

**Comment by tonyxue** [comment]
Updated. Like this?

**Comment by dnschneid** [comment]
Yep, thanks.

**Comment by cell13** [comment]
Oh,oh .So what can I do change the content ? The same problem.  " falied getting release file http://http.kali.org/kali/dists/sana.Release" .Thanks!

**Pull request merged**
