### PR TITLE
chroot-bin/croutonversion: Add xmethod

### PR DESCRIPTION
**Pull request by DennisLfromGA**
Show the current XMETHOD in the output.

### CODE REVIEW

**Comment by dnschneid** [comment]
Thanks!

**Comment by DennisLfromGA** [comment]
Back at'cha...

**Comment by aghasemi** [comment]
Hi,
Pardon I have a question regarding Crouton. Sorry if this is not the right place to ask.
Is it possible to run a command right from ChromeOS without loading the whole window manager inside Crouton? Something like "crouton gimp" or "crouton git ..." or "crouton javac ..."?

I'm considering buying a chromebook but I want to first make sure I can seemlessly run Linux on it.
Thanks

**Comment by dnschneid** [comment]
Not the right place to ask (normally you should open a new issue).  But as it turns out, I'm implementing just that on a side branch (xiwi-app).  Follow along in #558

**Comment by aghasemi** [comment]
Thanks a lot and sorry for the irrelevance.

**Pull request merged**
