### PR TITLE
Add license 1

### PR DESCRIPTION
**Pull request by TomTravis**
hello David
Screenshot_2022-11-21_12-03-18
I still have a active CLA with Google
The license activity is being addressed Test 3 is working fine it a complex change and not easy too create delta in github

My local activity is now backed up but no staged for github yet
Maybe by 2023 a new repo will be created forking is not the way

### CODE REVIEW

**Comment by dnschneid** [comment]
This is definitely too complex a change and has way too many extraneous files to be merged.

I strongly recommend starting your own repo for your work; I don't think you'll be getting much interest here.

**Comment by TomTravis** [comment]
David this is for your consideration no one else i am doing my own work
it appears i am required to work with you directly given the github instruction 
this is github asking for pull request with you not me

**Comment by dnschneid** [comment]
You may want to detach your fork so github stops trying to make pull requests: https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks

**Comment by TomTravis** [comment]
yes i know this git hub is using us to make instructions
i happy to help github

**Comment by TomTravis** [comment]
very well the post are deleted and the CLA was sent to Google legal test2 is now PW protected test3 is not released
https://www.reddit.com/r/Crouton/
you act very strange about this repo and i have no idea why

**Comment by TomTravis** [comment]
Hello,

Thanks for reaching out to us.

We have received your request.

We receive many such requests each day; your message is in our queue, and we'll get to it as quickly as our workload permits. Due to the large volume of requests that we receive, we will only be able to provide you with a response if we determine your request may be a valid and actionable legal complaint, and we may respond with questions or requests for clarification. For more information on Google's Terms of Service, please visit http://www.google.com/accounts/TOS

Regards,

The Google Team

Due to the impact of COVID-19, it may take us longer than usual to respond to your request. Our apologies for the inconvenience.

**Comment by dnschneid** [comment]
I'm not sure what you're expecting from the CLA.  Signing the CLA means you agree to hand over copyright for any patches you contribute to the repo.  It's a prerequisite for having your PRs accepted, but does not guarantee they won't be rejected.

**Comment by TomTravis** [comment]
that why im asking legal it say nothing in writing
this is you idea 
The author is google not you

**Pull request closed without merging**
