### PR TITLE
targets/audio: Patch up incorrect strncpy

### LINKED ISSUE #4118: Issue with kali-rolling
```
Please paste the output of the following command here: sudo edit-chroot -all

name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20190807171712~master:6f45f06a
release: kali-rolling
architecture: amd64
targets: x11,xorg,audio,gtk-extra,gnome
host: version 12404.0.0 (Official Build) canary-channel eve 
kernel: Linux localhost 4.4.186-16724-g284c626f060d #1 SMP PREEMPT Wed Aug 7 21:07:31 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
Error with buffer length in strncpy when installing kali-rolling

```
common/cras_shm.c: In function 'cras_shm_info_init':
common/cras_shm.c:29:2: error: 'strncpy' specified bound 255 equals destination size [-Werror=stringop-truncation]
  strncpy(info.name, stream_name, sizeof(info.name));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### If known, describe the steps to reproduce the issue:
set up kali with the command `sudo crouton -t x11,xorg,audio,gtk-extra,gnome -r kali-rolling`

### PR DESCRIPTION
**Pull request by drinkcat**
Fixes #4118, proper fix pending upstream.

### CODE REVIEW

**Comment by drinkcat** [comment]
(branch name should be cras-kali, I guess I'm watching too much Netflix...)

**Comment by drinkcat** [comment]
`2019-08-18_11-03-39_drinkcat_chroagh_cras-cali_30`

**Comment by dnschneid** [comment]
I think you need to rebase against master and run the test again.  You're missing the cras_test_client.c fix

**Comment by dnschneid** [comment]
Looking good.  Should we merge this though, considering the patch got submitted before branching?

**Comment by drinkcat** [comment]
Bug introduced in https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1637726/ (R77-12262.0.0)

And fixed in
https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1759370 (R78-12440.0.0)

This spans a branch and I'm probably not going to merge request to R77, so we want to merge this.

**Pull request merged**
