### PR TITLE
Change the license to 2015

### PR DESCRIPTION
**Pull request by tonyxue**
There was a pull request have done this but only for a single file and did not get updated and seems disappeared?
I'm picky so I just did this :P

I did this by using script to simply replace 2014 to 2015. Hopefully I did not break anything else.

### CODE REVIEW

**Comment by dnschneid** [comment]
Thanks!  There's some 2013s lingering around too...

**Comment by tonyxue** [comment]
Fixed

**Comment by tonyxue** [comment]
@dnschneid Let's merge!! Half of 2015 will pass soon!!! Not very long this patch will work! :P

**Comment by dnschneid** [comment]
Aww snap, you're right!  We're almost out of time!

**Pull request merged**
