### PR TITLE
Update targets/gnome

### PR DESCRIPTION
**Pull request by Linux-Distros**
Change gnome-session-fallback to gnome-session-flashback for Vivid And Up

### CODE REVIEW

**Comment by Linux-Distros** [comment]
Yes But It Has Been Many Months Since, An Ideas When Its Going To Be Fixed?

**Comment by DennisLfromGA** [comment]
Yes, When The Original PR Author Fixes The Syntax Glitches And Submits Them.

Simply Submitting A Copy Of The Same PR With The Same Glitches Isn't Going To Help - *At ALL*.

**Comment by Linux-Distros** [comment]
Sorry

**Comment by DennisLfromGA** [comment]
No problem. 
Adding a duplicate PR just adds to the developers already busy workload, that's all.

**Pull request closed without merging**
